-- Feedback table definition
CREATE TABLE public.feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    rating INTEGER DEFAULT 5,
    is_approved BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    user_id BIGINT REFERENCES public.users(id)
);

-- Enable Row Level Security
ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Anyone can insert feedback" 
    ON public.feedback FOR INSERT 
    WITH CHECK (true);

CREATE POLICY "Public can view approved feedback" 
    ON public.feedback FOR SELECT 
    USING (is_approved = TRUE);

CREATE POLICY "Admin users can manage all feedback" 
    ON public.feedback FOR ALL 
    USING (EXISTS (SELECT 1 FROM public.users WHERE email = auth.uid()::text AND is_admin = TRUE)); 