-- Scan Exports table definition
CREATE TABLE public.scan_exports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id VARCHAR(255),
    target_host VARCHAR(255) NOT NULL,
    export_format VARCHAR(50) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    file_size BIGINT,
    user_id BIGINT REFERENCES public.users(id),
    scan_date TIMESTAMP WITH TIME ZONE,
    export_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    port_count INTEGER DEFAULT 0,
    open_port_count INTEGER DEFAULT 0,
    summary TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE public.scan_exports ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Users can view their own exports" 
    ON public.scan_exports FOR SELECT 
    USING (user_id = (SELECT id FROM public.users WHERE email = auth.uid()::text));

CREATE POLICY "Users can insert their own exports" 
    ON public.scan_exports FOR INSERT 
    WITH CHECK (user_id = (SELECT id FROM public.users WHERE email = auth.uid()::text));

CREATE POLICY "Admin users can view all exports" 
    ON public.scan_exports FOR ALL 
    USING (EXISTS (SELECT 1 FROM public.users WHERE email = auth.uid()::text AND is_admin = TRUE)); 