-- Users table definition
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL, -- This stores "managed-by-supabase-auth" as auth is handled by Supabase Auth
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_admin BOOLEAN DEFAULT FALSE
);

-- Enable Row Level Security
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Users can view their own data" 
    ON public.users FOR SELECT 
    USING (auth.uid()::text = email);

CREATE POLICY "Admin users can view all data" 
    ON public.users FOR ALL 
    USING (EXISTS (SELECT 1 FROM public.users WHERE email = auth.uid()::text AND is_admin = TRUE)); 